### ISSUE TITLE
Copy/pasted Deprecated comment in LengthHaversine

### ISSUE THREAD

**Issue by jfbus** [paulmach/orb#100]
The LengthHaversine func has a `Depredated` comment that should not be there:
```
// Deprecated: misspelled, use correctly spelled `LengthHaversine` instead.
func LengthHaversine(g orb.Geometry) float64 {
```

**Comment by paulmach** [comment]
Thank you for taking the time to report this. Fixed in https://github.com/paulmach/orb/commit/e14170606937b8eb2cb201377f09c4bfdd73ba47
