### ISSUE TITLE
The resulting MVT is too big (27MB)

### ISSUE THREAD

**Issue by SulimanLab** [paulmach/orb#103]
Hi, 

I have a large geojson file (500 MB) that i try to load in mapboxgl for performance reasons I needed to convert into vector tiles. 

The issue is that it still return large mvt tiles size (around 27MB) which causes the mapbox to hang and gets laggy.

Is there a way to `limit` the number of features that is projected to a tile ?

**Comment by paulmach** [comment]
sure, filter them out.

But maybe your looking for something like https://github.com/mapbox/tippecanoe

**Comment by SulimanLab** [comment]
As far as I know tippecanoe works with static files,  and there is no go/python API for it. 

Can I achieve that without filtering them, lowering the resolution for example ? or limiting the resulting features ? 

I have tested the same data with this project  https://github.com/CrunchyData/pg_tileserv and the resulting tiles are significantly smaller (from 10MB to 500KB)
