### ISSUE TITLE
Units of orb.Bound.Pad()

### ISSUE THREAD

**Issue by tlelson** [paulmach/orb#105]
Perhaps I've missed something elsewhere in the documentation but what exactly are the units to this function.

It looks roughly like 10's Km's from trial and error. 

https://pkg.go.dev/github.com/paulmach/orb@v0.7.1#Bound.Pad

**Comment by paulmach** [comment]
Pad just adds the number.

https://github.com/paulmach/orb/blob/6f098c10dc864dc4c5c0b993554f96c6fbb245cc/bound.go#L104-L112

**Comment by tlelson** [comment]
Thanks @paulmach. I think I understand the package on a whole much better now too.
