### ISSUE TITLE
Subdivide polygon

### ISSUE THREAD

**Issue by AgentNemo00** [paulmach/orb#114]
Hello,

I'm trying to subdivide a polygon into sub polygons as described in this [[post](https://gis.stackexchange.com/a/375130)](https://gis.stackexchange.com/a/375130).
Has anyone ever archieved a this ?

**Comment by paulmach** [comment]
Well, if you know where you want to draw the lines and the sections are boxes you can use the [smartclip](https://github.com/paulmach/orb/tree/master/clip/smartclip) subpackage to cut the large polygon. 

Figuring out where to cut is another matter. I'm sure the general case would be really hard, but if you could determine a starting point you could optimize it in a loop by adjusting the lines accordingly. ?
