### ISSUE TITLE
How to update DefaultRoundingFactor for Lat/Lon?

### ISSUE THREAD

**Issue by arif2009** [paulmach/orb#125]
I need Lat()/Lon() up to 8 decimal places, but it always returns 6 decimal places. How can I upgrade it to 8?

**Comment by arif2009** [comment]
@paulmach It is not working because here https://github.com/paulmach/orb/blob/v0.9.0/define.go#L8 it restrict upto 6 decimal places

**Comment by paulmach** [comment]
that's `DefaultRoundingFactor` used for rounding. And you can change it

Can you provide some more context on "always returns 6 decimal places". What returns only 6?

**Comment by arif2009** [comment]
My code is like this:
```
m := minGeomScan.Geometry.(orb.Point)
ml := jsonschema.LatLon{
	Lng: m.Lon(),
	Lat: m.Lat(),
}
```
where m.Lon() & m.Lat() always returns up to 6 decimal places, but I need it to make 8.

**Comment by paulmach** [comment]
m.Lat() and m.Lng() do not return 6 decimal places. They return a [float64](https://github.com/paulmach/orb/blob/master/point.go#L39).

This is related to you're input, how you're parsing data to create the `minGeomScan` or your output, how you can see the 6 decimal places.
