### ISSUE TITLE
Addition key/value pairs for FeatureCollection

### ISSUE THREAD

**Issue by Klaus-Tockloth** [paulmach/orb#13]
Currently I have this:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
...
```

I want to add some generator information:
```
{
  "type": "FeatureCollection",
  "generator": "printmaps",
  "timestamp": "2018-10-23T06:21:02Z",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
...
```

Question: Is this somehow possible?

**Comment by paulmach** [comment]
For unmarshaling on the feature collection it's not to bad, you basically define a wrapper type. Longer explanation here https://github.com/paulmach/orb/issues/1#issuecomment-364706497

For marshaling the only solution I can think of requires some reflections.

Are you interested in marshaling, unmarshaling, or both?
