### ISSUE TITLE
Invalid MULTIPOLYGON no longer gives an error

### ISSUE THREAD

**Issue by gellyfisher** [paulmach/orb#130]
I would expect to get an error in the following MULTIPOLYGON because there is no closing bracket at the end. However since 0.9.1 this doesn't happen anymore. Is this intended ? 

```
package main

import (
	"fmt"

	"github.com/paulmach/orb/encoding/wkt"
)

func main() {
	ret := "MULTIPOLYGON(((0 1,3 0,4 3,0 4,0 1)), ((3 4,6 3,5 5,3 4)), ((0 0,-1 -2,-3 -2,-2 -1,0 0))"
	_, err := wkt.UnmarshalMultiPolygon(ret)
	fmt.Printf("error: %s", err)
}
```

**Comment by paulmach** [comment]
fixed in https://github.com/paulmach/orb/pull/131

**Comment by gellyfisher** [comment]
Thanks for the quick resolution!
