### ISSUE TITLE
Degraded performance wkt.Unmarshal since v.0.9.1 

### ISSUE THREAD

**Issue by doqtri** [paulmach/orb#132]
Hi,

I've noticed the degraded performance of the method **wkt.Unmarshal** since **_v.0.9.1_** 
Here is the comparison 

**v.0.9.0**
```
BenchmarkUnmarshall_V90-10
BenchmarkUnmarshall_V90-10    	   55581	     21352 ns/op	   11384 B/op	     101 allocs/op
```

**v.0.9.1**
```
BenchmarkUnmarshall_V91-10
BenchmarkUnmarshall_V91-10    	    9172	    121703 ns/op	   17722 B/op	     180 allocs/op
```

**Comment by paulmach** [comment]
looks like 
* https://github.com/paulmach/orb/pull/128

and then
* https://github.com/paulmach/orb/pull/131

There were a few issues about validation that these addressed. PRs welcome.

**Comment by paulmach** [comment]
performance has been improved to much greater than v0.9.0 levels in https://github.com/paulmach/orb/pull/142 See benchmarks in that PR.

The exception is very small geometries with multiple parts (multi*, polygon). The splitting of the parts still uses the regexp. However, in most cases the improvements to the "point parsing" will greatly out-way any issues.
