### ISSUE TITLE
Parsing of WKT

### ISSUE THREAD

**Issue by Succo** [paulmach/orb#14]
Would you interested in adding support for parsing WKT?

If so I'd be up to try that.

**Comment by paulmach** [comment]
Yes, that would be great. The API should be similar to the wkb package. https://godoc.org/github.com/paulmach/orb/encoding/wkb

**Comment by Succo** [comment]
Great.
I've worked on a prototype https://github.com/Succo/wktToOrb/ I'll paly with it/test it a little bit more and come back toward you when it fits the wkb API?

**Comment by fredrickprashanth** [comment]
Is there plan to support Google polyline string in wkt ?

**Comment by paulmach** [comment]
support for parsing wkt was added Jan 2021. https://github.com/paulmach/orb/pull/59
