### ISSUE TITLE
When i use a large polygon and clip it,it looks bad

### ISSUE THREAD

**Issue by liujiusheng** [paulmach/orb#143]
![problem image](https://github.com/paulmach/orb/assets/9045263/29f26755-88ec-4efd-b7f2-1eaa2c11d358)

When i use a large polygon to generate Mapbox Vector Tile,it looks bad.
But it has no problem in mapbox studio,with the same data.
My data is a China province boundary.

![data in mapbox studio](https://github.com/paulmach/orb/assets/9045263/e6526c11-43eb-4707-8634-d32203da271a)

I have try to remove the Clip function,and then it looks right,but the result mvt binary is too big.

```
tile := maptile.New(x, y, maptile.Zoom(z))
layer := mvt.Layer{
Name:    path,
Version: 2,
Extent:  4096,
//Features: geoFeatures,
}
layer.Features = Tile(layer, geoFeatures, tile, fields)
layer.Clip(mvt.MapboxGLDefaultExtentBound)

layer.Simplify(simplify.DouglasPeucker(0.0))
layer.RemoveEmpty(1.0, 1.0)
layers := mvt.Layers{&layer}
return mvt.Marshal(layers)
```

**Comment by paulmach** [comment]
Can you provide the data and tile number for the province, so I can debug? Possible issues are polygon not closed (endpoints not the same), or the wrong winding order. But hard to know without the actual data.

**Comment by liujiusheng** [comment]
thanks.

[shpdata.zip](https://github.com/paulmach/orb/files/13958889/shpdata.zip)

it may happen when zoom>9

z: 10,x: 817,y: 422

z: 10,x: 816,y: 421

z: 10,x: 816,y: 420

the ring function in [orb](https://github.com/paulmach/orb/blob/8c80c614d4077bb2175de23b311e54acfe27fceb/clip/clip.go#L85C49-L85C49) lead to the problem when the clip bound is in the polygon and whitout intersect with the polygon outline.

**Comment by paulmach** [comment]
<img width="474" alt="Screenshot 2024-01-27 at 8 40 35 PM" src="https://github.com/paulmach/orb/assets/366320/a3394a02-e729-4632-97e1-0a6c6f41325a">

I am not able to duplicate.

One thing to consider is that Clip modifies the input data. If you need to reuse it then you need to `Clone()` it before passing it in.

**Comment by liujiusheng** [comment]
thanks. Maybe it recurrence only when we render the whole map.
 mapbox mapbox/tippecanoe project use Vatti algorithm called "wagyu"，your clip algorithm is Sutherland-Hodgeman clip algorithm.
Sutherland-Hodgeman clip algorithm can not deal with polyon with hole and Concave polygon.

**Comment by paulmach** [comment]
> Sutherland-Hodgeman clip algorithm can not deal with polyon with hole and Concave polygon.

Is that true? the [wikipedia page](https://en.wikipedia.org/wiki/Sutherland%E2%80%93Hodgman_algorithm) has an example of a concave polygon. From the [Vatti clipping algorithm wikipedia page](https://en.wikipedia.org/wiki/Vatti_clipping_algorithm) it says it support "Even complex (self-intersecting) polygons" which I bet Sutherland-Hodgeman doesn't support.

You could try https://github.com/paulmach/orb/tree/master/clip/smartclip I don't remember how it handles all the edge cases, but it is smarter.
