### ISSUE TITLE
Change Point from [2]float64 to just []float64

### ISSUE THREAD

**Issue by avikomarlingam** [paulmach/orb#155]
The point type is currently defined as a slice of fixed length 2, which leads to a few problems when attempting to validate inputs. Using any types from this package will just result in any coordinates that are missing either a lat/lon being padded with a 0. There are even cases where this padding results in a geometry that is still valid, as seen in this go playground link: https://go.dev/play/p/qFsJHRSgHAC.

**Comment by paulmach** [comment]
[2]float64 is 2x64 bytes.  []float64 is pointer to a slice header which has a pointer to the data. It is slower. 

I understand the pros and cons but I'm not going to change this.
