### ISSUE TITLE
Deep copy of FeatureCollection and Feature?

### ISSUE THREAD

**Issue by s8mathur** [paulmach/orb#2]
Paul, 

Do you have any guidance on how to solve this use case?

Step 1: I have an input GeoJSON that has dozens of hexagonal `Polygon`s for a given city. I unmarshal this and have a `FeatureCollection` or its wrapper struct initialized. 

Step 2: After binning a million geo-tagged input data samples from say three mobile networks ("Sprint", "AT&T", "Verizon") into each of the above-mentioned hexagonal bins, I have some statistics for a given network for each of the grids (`Features`) with the city. 

 Step 3: I wish to now serialize three GeoJSONs (one per mobile network) with all of the information from Step (1) + stats from Step (2) inserted inside Feature->Properties->"QoS".  With these GeoJSONs, I have easy ability to build three independent data sources for the mobile networks. 

The problem: Since we use `*FeatureCollection` and `*Feature` everywhere, the only way to initialize a fresh copy of `FeatureCollection` and `Feature` that can be stuffed with an independent copy of "extra" data (such as Sprint's metrics for a hexagon without clobbering Verizon's stats) is to Marshal and Unmarshal to text repeatedly. 

What am I missing? :)

**Comment by paulmach** [comment]
I think adding a `Clone` method to features and feature collections would be okay. 

There are a number of ways you can do this currently

1. you can clone the features yourself: the properties and the geometry both have clone methods.
2. you can use an intermediate object like:
```
type Bin struct {
  Polygon orb.Polygon
  Count int
}
```
Then add some methods like `AddPoint` or whatever. Once it's all done covert that to a feature collection.

**Comment by s8mathur** [comment]
Thank you! I will attempt to use the existing clone in geometry and properties.
