### ISSUE TITLE
Max points limit of 5000 when decoding WKB

### ISSUE THREAD

**Issue by PetarLotrean** [paulmach/orb#26]
Hi,

I am loading polygons that have many points, e.g. Swiss cantons have >10k points. This limit (maxPointsAlloc) just cuts everything to 5k, which would be fine if the cutoff didn't mess silently with the polygon - if there is only one Ring, there will be just the first 5k points, and if there are multiple Rings, decoding produces garbage data, and that is noticed only when actually looking at the data.

Also, it is not currently possible to change this limit, it is hard coded.

I would add a way to change the global limit, or add limit per decoder when constructing the object.

I would also add an error when the number is over the limit.

I am willing to invest some time to fix this, but I am asking here first in case there is some reason that this exists at all? It might as well be removed.

**Comment by paulmach** [comment]
Yes, this a bug. I'll post a PR later tonight.

Intentions was to limit how much memory could be preallocate. Malformed input could say there were 1billiion points in a linestring, it needs a max to avoid an Out of Memory error. But it also limited the number read too, which is wrong.

**Comment by PetarLotrean** [comment]
Great, thanks! Great work, BTW 🙂

**Comment by paulmach** [comment]
created https://github.com/paulmach/orb/pull/27 to fix this. Will probably merge in the morning
