### ISSUE TITLE
Missing check if tile projected coordinates are in larger extent

### ISSUE THREAD

**Issue by karsten42** [paulmach/orb#3]
In order to use the generated vector tiles as a source for mapbox all coordinates in a tile must not exceed a certain extent. (https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-vector)

https://github.com/paulmach/orb/blob/1f34bf6ee9935efca353b8cc0e06396d347cf836/encoding/mvt/projection.go#L27-L31
Maybe the projection could also return if the point should be included or not?

Was this check left out by choice?

**Comment by paulmach** [comment]
thanks for taking a close look at this, should probably return an error when marshaling. Interestingly I don't see any reference to these bounds in https://github.com/mapbox/vector-tile-spec

I'm on vacation this week, will take a closer look into this next week.

**Comment by paulmach** [comment]
Okay, so I had some time to think about this. This requirement seems to be just for mapbox gl and not necessarily something that's required by the spec. Thus I think it should be left out here. 

I think the user should clip the geometry to a little more than the tile bound. You can use the [clip](https://github.com/paulmach/orb/tree/master/clip) sub-package to do that.

**Comment by karsten42** [comment]
Fair enough.
I think it would make sense to have this functionality on the layers then, see #5.
What do you think?

**Comment by paulmach** [comment]
merged #5  thank you.
