### ISSUE TITLE
incorrect result from Quadkey()

### ISSUE THREAD

**Issue by rythmkraze** [paulmach/orb#35]
As per [bing maps](https://docs.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system
), given tile XY coordinates of (3, 5) at level 3, the result should be a string `“213”`. 

But Quadkey() from orb package for the same tile returns a uint64 of `39`. Why are the results different?
`func (t Tile) Quadkey() uint64`

**Comment by paulmach** [comment]
Hi,

The bing maps webpage displays the QuadKey in base 4, i.e. every digit indicates which of the 4 subtiles to consider at that level. Something like `fmt.Println(t.Quadkey())` will print the number is base 10.  39 base 10 -> 213 in base 4. 

modeling the quadkey as a uint64 is more efficient. Both in space and allows for some fast bit operations.

**Comment by rythmkraze** [comment]
Thanks for the explanation, Paul.

**Comment by rythmkraze** [comment]
Follow up question. 

Why does `FromQuadkey` require zoom level as input, can't that be inferred from the length of the quadkey in base 4 form?

`func FromQuadkey(k uint64, z Zoom) Tile
`

**Comment by paulmach** [comment]
The zoom can be inferred from the string key. i.e. length of the string.  But for a unit64 key you don't know if the leading zeros mean more zoom or not.  For example the top left tile will be all zeros for every zoom.

**Comment by rythmkraze** [comment]
Thanks
