### ISSUE TITLE
Issue when retrieving postgis geometry

### ISSUE THREAD

**Issue by arthurgustin** [paulmach/orb#36]
I've spend a couple of hours trying to figure out what doesn't work with my use-case (`postgreSQL`, `postGIS`, `go-pg` and `orb`)

I have a complicated `SELECT` query (2 joins and 1 pivot) that I will simplify for this thread. The problem occurs during the Scan of a polygon 

```
p := orb.Polygon{}
_, err := b.Database.Query(wkb.Scanner(&p), `SELECT ST_AsBinary(jobs.region,'NDR') FROM jobs LIMIT 1`, id)
```

The returned error:

```
Expected
          <internal.Error>: {
              s: "wkb: invalid data",
          }
      to be nil
```

I dig in the code and found that the error occurs here: https://github.com/paulmach/orb/blob/5af0ae28533d2d7038e9e103c43ccc6d8d0d05a6/encoding/wkb/wkb.go#L218-L244

I added some logs to print the actual data and I got this:

```
\x01030000000200000005000000000000000000000000000000000000000000000000002440000000000000000000000000000024400000000000002440000000000000000000000000000024400000000000000000000000000000000005000000000000000000f03f000000000000f03f000000000000f03f0000000000000040000000000000004000000000000000400000000000000040000000000000f03f000000000000f03f000000000000f03f
```

which seems to be a perfect WKB apart from the leading `\x`. When I use a online service like https://rodic.fr/blog/online-conversion-between-geometric-formats/ to convert the data it gives exactly what I inserted in the database --> `POLYGON((0 0,10 0,10 10,0 10,0 0),(1 1,1 2,2 2,2 1,1 1))`

Any ideas ?

**Comment by paulmach** [comment]
Had this issue with go.geo https://github.com/paulmach/go.geo/issues/66 . The data comes back as hex and not binary. I will work on a fix.

**Comment by paulmach** [comment]
Fix here https://github.com/paulmach/orb/pull/37

I tested locally with Point datatype.  Testing with other types would be helpful.  Thank you.

**Comment by arthurgustin** [comment]
I tested my code with your branch and it works fine.

My code (simplified) for inserting:

```golang
type job struct {
	JobID            string       `sql:"job_id,pk"`
	Region           orb.Geometry `sql:"region"`
}

const insertJobquery = `INSERT INTO jobs VALUES (?,ST_GeomFromEWKB(?))`

res, err := b.Database.Exec(insertJobquery,
		job.JobID,		
		wkb.Value(job.Region),
	)

```

My code (simplified) for retrieving:

```golang

const getJobquery = `
SELECT jobs.job_id,ST_AsBinary(jobs.region)
FROM jobs
WHERE jobs.job_id = ?`

orbPolygon := orb.Polygon{}
res, err := b.Database.Query(pg.Scan(
	&dbJob.JobID,		
	wkb.Scanner(&orbPolygon),		
), getJobquery, id)

// handle region

dbJob.Region = orbPolygon

```

I don't have time to improve your MR unfortunately, but thank you a lot for your quick fix !

**Comment by paulmach** [comment]
I merged https://github.com/paulmach/orb/issues/36 and tagged v0.1.5
