### ISSUE TITLE
Problems with UnmarshallingFeatureCollection with "GeometryCollection"

### ISSUE THREAD

**Issue by joernkleinbub** [paulmach/orb#39]
I have some problems with "GeometryCollection"s. I want to unmarshall "FeatureCollections" with "GeometryCollection"  from GeoJSON.

I simplified the imported GeoJSON for testing purposes
```
{
  "type": "FeatureCollection",
  "name": "other_relations",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "osm_id": "175387"
      },
      "geometry": {
        "type": "GeometryCollection",
        "geometries": [
          {
            "type": "Point",
            "coordinates": [
              6.2169758,
              49.6411581
            ] } ] } } ]}
```
I get the error: geojson: invalid geometry

I digged a little bit:
It seems that Geometry is not unmarshalled well. 
https://github.com/paulmach/orb/blob/f23a70574f58f05fc956f6b2c57e1604dfde8d1c/geojson/geometry.go#L105-L113
The `type` for the `g *geometry` is not defined for a `jq jsonGeometry`.

https://github.com/paulmach/orb/blob/f23a70574f58f05fc956f6b2c57e1604dfde8d1c/geojson/feature.go#L81-L83
`jf.Geometry.Coordinates`: A GeometryCollection has no `coordinates`. it has `geometries`. So the result will always be false.

https://github.com/paulmach/orb/blob/f23a70574f58f05fc956f6b2c57e1604dfde8d1c/geojson/feature.go#L85-L91
`Geometry:   jf.Geometry.Coordinates`: A GeometryCollection has `geometries`

At that point I stopped digging. I am not sure how to proceed to solve that issue?

**Comment by paulmach** [comment]
Closed/fixed by #44 Thank you.
