### ISSUE TITLE
Add repo to awesome-vector-tiles

### ISSUE THREAD

**Issue by karsten42** [paulmach/orb#4]
Awesome-vector-tiles (https://github.com/mapbox/awesome-vector-tiles) provides a list of libraries that are able to deal with vector tiles. 
Maybe you could add yours there, because they are lacking a good golang library.

**Comment by paulmach** [comment]
I created this PR https://github.com/mapbox/awesome-vector-tiles/pull/49

**Comment by paulmach** [comment]
thanks for the suggestion, my addition was merged in less than 10 minutes!
