### ISSUE TITLE
Mapbox Vector Tile Unmarshal Failed: proto: wrong wireType = 7 for field Layers

### ISSUE THREAD

**Issue by wangyoucao577** [paulmach/orb#40]
I downloaded the sample `mvt` from Mapbox to try the [encoding/mvt](https://godoc.org/github.com/paulmach/orb/encoding/mvt) library, but error occurred when unmarshal  it.       

The `mvt` file comes from:      
```bash
curl https://api.mapbox.com/v4/mapbox.mapbox-streets-v6/9/150/194.mvt\?access_token\=YOUR_MAPBOX_ACCESS_TOKEN  >3.mvt
```

My code looks like:     
```go
		content, err := ioutil.ReadFile("3.mvt")
		if err != nil {
			log.Fatal(err)
		}

		layers, err := mvt.Unmarshal(content)
		if err != nil {
			log.Fatal(err)
		}
```

Then I got error `2020/02/03 11:00:35 proto: wrong wireType = 7 for field Layers`.      

But use the tool [mapbox/vt2geojson](https://github.com/mapbox/vt2geojson) I can get unmarshalled `geojson` successfully: 
```bash
vt2geojson https://api.mapbox.com/v4/mapbox.mapbox-streets-v6/9/150/194.mvt\?access_token\=YOUR_MAPBOX_ACCESS_TOKEN >3.json
```

Anything wrong with the [encoding/mvt](https://godoc.org/github.com/paulmach/orb/encoding/mvt) library? 

I have uploaded both the `.mvt` and `.json` in the [3.zip](https://github.com/paulmach/orb/files/4146092/3.zip), FYI.

**Comment by wangyoucao577** [comment]
I made a simple command line tool `vt2geojson` based on this library, which supports load `mvt` from either file or URL. The strange thing is it's ok to download from URL directly, but it reports this error from file, even from the file in `encoding/mvt/testdata`.      

Please refer to the command line tool from: https://github.com/wangyoucao577/orb/tree/feature/vt2geojson/cmd/vt2geojson

```bash
$ cd cmd/vt2geojson
$ go build 
$ 
$ ./vt2geojson -mvt ../../encoding/mvt/testdata/15-8956-12223.mvt -summary
2020/02/03 15:52:51 proto: wrong wireType = 7 for field Layers
```

**Comment by invisiblefunnel** [comment]
I believe this failure is due to the data being gzipped. Try to gunzip the file or use `mvt.UnmarshalGzipped`.

**Comment by wangyoucao577** [comment]
You're right. It works after use `mvt.UnmarshalGzipped` instead. Previously the `.mvt` comes from http works because the `http.Get` will silently uncompress the response if see `Content-Encoding: gzip`. 

The `.mvt` comes from mapbox server is always gzipped, whatever with `Accept-Encoding: gzip` or not. I didn't see any explaination from mapbox document about the `gzip`. It looks like an implementation issue of mapbox's vector tile service.
