### ISSUE TITLE
Wrong output from mysql

### ISSUE THREAD

**Issue by si3nloong** [paulmach/orb#48]
```go
c1 := new(sql.RawBytes)
c2 := orb.Point{}
c3 := orb.Point{}
client.QueryRow("SELECT `ID`,`Point`,`PtrPoint` FROM `sqlike`.`spatial` WHERE `ID` = 1 LIMIT 1;").Scan(&c1, wkb.Scanner(&c2), wkb.Scanner(&c3))
```

This is the code snippet of my program, the expected value for `c2` is `Point [1 5]`, but it showed `Point [7.291122019556398e-304 1.30509107131737e-309]` instead. This problem occurs because MySQL returning the binary in format of `SRID+WKB`, every data retrieve back from MySQL we should truncate the first 4 bytes. You may refer to the below snippet.

```go
	case *orb.Point:
                 // Most likely MySQL's SRID+WKB format.
		if len(data) == 25 {
			data = data[4:]
		}
		p, err := scanPoint(data)
		if err != nil {
			return err
		}
```

**Comment by paulmach** [comment]
This is fixed. The code will try to decode wkb, if the prefix is invalid, it'll remove the first 4 bytes (SRID) and try again.
