### ISSUE TITLE
update geojson properties

### ISSUE THREAD

**Issue by paleozogt** [paulmach/orb#52]
Over at [go.geojson](https://github.com/paulmach/go.geojson), the library has `PropertyBool`, `PropertyInt`, etc, but the version of geojson in orb doesn't.  Also one uses `PropertyMustBool` while the other uses `MustBool`, etc.

Could we get the geojson that's in orb to match what's in [go.geojson](https://github.com/paulmach/go.geojson)?

**Comment by paulmach** [comment]
different doesn't mean bad. I think the orb way is cleaner than the old go.geojson way.
