### ISSUE TITLE
Render mbtiles

### ISSUE THREAD

**Issue by mathisloge** [paulmach/orb#6]
Hey there, just a quick question: 

Get we generate mbtiles with this project and use those with the klokantech/tileserver-gl? 
If yes, wich source is recommended? Can we use the .osm.pbf file? 

Thanks in advance

**Comment by paulmach** [comment]
This library probably can't do what you want. This library can convert GeoJSON type data into MVT type data. But it doesn't do the clipping and doesn't do pack all the tiles into a *.mbtiles format.
 
This library is pretty low level compared to something like https://github.com/mapbox/tippecanoe
