### ISSUE TITLE
GeoJSON : Elevation

### ISSUE THREAD

**Issue by zdannar** [paulmach/orb#60]
Hello Paul,

Orb is a fantastic library and thank you for all of your hard work.  It appears that geoJson supports and optional field in the coordinates specifying an elevation.   Are you planning on supporting this in the future? 

Thanks again for the great library.

**Comment by paulmach** [comment]
Do you mean 3d coordates like [x, y, z]?  If so, no, orb is 2d as the Point type is defined as `[2]float64`.  You could fork this and make the change, or you could use https://github.com/paulmach/go.geojson if you're just interested in geojson encoding/decoding.

**Comment by zdannar** [comment]
Thanks for the clarification Paul.  I will have to consider my options.
