### ISSUE TITLE
go.mod not working, unknown revision v0.2.0

### ISSUE THREAD

**Issue by si3nloong** [paulmach/orb#65]
<img width="989" alt="Screenshot 2021-04-08 at 10 16 43 PM" src="https://user-images.githubusercontent.com/28108597/114042641-2f4e5800-98b8-11eb-9626-422edc25085a.png">

**Comment by paulmach** [comment]
maybe not up-to-date. it's there https://github.com/paulmach/protoscan/tags

**Comment by si3nloong** [comment]
Please refer to the PR https://github.com/paulmach/protoscan/pull/1, afterward we need to upgrade the go.mod for this package as well

**Comment by si3nloong** [comment]
pr #66 should fixed this issue

**Comment by paulmach** [comment]
merged https://github.com/paulmach/orb/pull/66
