### ISSUE TITLE
API question: Quadree + Pointer interop with GeoJson types

### ISSUE THREAD

**Issue by s8mathur** [paulmach/orb#7]
So my heart a skipped a beat or two when I noticed that there is a now a QuadTree implementation. THANK YOU! :)

I am reading a tens of thousands of hexagons in a city from a single GeoJSON file. Naturally, I upon using `UnmarshalFeatureCollection`, I end up with a bunch of `Polygon` feature (not `Ring`, even though they suffice for my use case) 

Now, if I start from the problem statement: "How do I use this Quadtree implementation to find which hexagon (if any) do these million points lie in", I initialize a QuadTree and then notice that I must have an `orb.Pointer`, which none of the `geojson` types implement out-of-the-box. 

Therefore, the sequence of steps to initialize a QuadTree and uniquely identify the hexagon where an input `Point` lies must be as follows. Does this sound right? 

1. Parse GeoJSON `FeatureCollection` using `UnmarshalFeatureCollection`

2. Create a wrapper struct type that (a) implements `orb.Pointer` perhaps by calculating centroid of Lat and Lng vertices of the wrapped `geojson.Polygon`, (b) encapsulates a `geojson.Polygon` , and (c) keeps track of index of `geojson.Polygon`  in the `geojson.FeatureCollection` slice from (1) above.

3. Iterate through the `FeatureCollection` and `make` and `Add()` the wrapped struct type to the QuadTree

4. Use `Find()` to identify the hexagon given a `orb.Point` to search, type assert the returned `orb.Pointer` to the wrapper type and extract index from (2)(c) to lookup the index number from the `geojson.FeatureCollection` slice. 

The two questions I am wondering about : 
a) Should key types on package `geojson` have a stock implementation of `orb.Pointer` ?
b) Should there be more a natural way to process the return value of `Find()` to the collection of items fed into the QuadTree?

Thanks,
Siddharth

**Comment by paulmach** [comment]
Thank you providing this use case.

a) Yes a `Point() Point` should be added to the geojson.Feature type. What do you think about just making the center of the bound the default? For something more custom one would have to create their own wrapper type.

b) I don't really understand. If a) is done, then you'd just feed in the features directly and not have to reference back to the collection using an index, e.g. `qt.Find(p).(*geojson.FeatureCollection)`.  Even without a) you could do that with your custom type.

**Comment by s8mathur** [comment]
Yes you may ignore (b), because returning the reference back is sufficient indeed. My data structures are laid out oddly. 

On (a), +1 to adding center of bound as default `Point()` for `geojson.Feature` types. Perhaps with a clear documentation note that this is may not be "accurate" depending on the use case, and that clients should feel encouraged to do roll their own interface implementation that is most appropriate for their geometry or application.

**Comment by paulmach** [comment]
This questions was resolved by having `geojson.Feature` implement the pointer interface used by the quadtree. Added in https://github.com/paulmach/orb/pull/8 see the accompanying examples.
