### ISSUE TITLE
Supporting circles as a native data type

### ISSUE THREAD

**Issue by thehoneymad** [paulmach/orb#81]
Hello,

Would you interested in adding support for circles as a native data type? 

At least planar circles, not spherical caps. I know it is a curve, not a well defined polygon. It is also not supported by WKT.

But, it does help a use case I currently work with. And since I use Orb as my de-facto geometry library here, I'd like to implement the feature myself for Orb.

It could be a struct with a point inside or a []float64{} with 3 members. The latter might impede in supporting 3D points in future.

**Comment by thehoneymad** [comment]
Hello @paulmach, leaving another comment here for visibility. :) Would really appreciate a reply here.

**Comment by paulmach** [comment]
I'm don't really want to support circles, or weighted points, as they don't correspond to a GeoJSON data type. Complicates the interop.

I also don't have any experience with this and don't know the use cases so it's going to be hard to know what to implement. It really seems more "geometry" vs. "geography" but what do I know.

I think it should be a separate library.

**Comment by thehoneymad** [comment]
That makes sense. I am not that knowledgeable either. I understand the rationale of not supporting circles, because its a curve, not a defined polygon. I assumed the same.

I do not have that much experience either. I added limited support for circles that allows my work to go on in a local branch. 

I also use a lot of orb flavoured libraries such as geobuf implementation here -> https://github.com/cairnapp/go-geobuf.

May be I could create a new library with curves support and as orb as a dependency. Thank you for replying. :) 

I love this library, fan of your work. Thank you! :)
