### ISSUE TITLE
Would you be open to changing the signatures in maptile/tilecover ?

### ISSUE THREAD

**Issue by thisisaaronland** [paulmach/orb#82]
Specifically, changing the return values from `maptile.Set` to `(maptile.Set, error)`

My concern is that the `/maptile/tilecover/polygon.go` code triggers a `panic` if it encounters an invalid geometry and it would be helpful for the package to return an error that I can handle in my application code rather than all the scaffolding necessary to trap and recover from a panic.

I am happy to do the work to produce a PR but figured I would see whether this was interesting to you, first.

**Comment by paulmach** [comment]
I created this PR to return an error https://github.com/paulmach/orb/pull/87

I'm not sure what the protocol is for changing the signature. Can I just minor version bump it since we're not 1.0 yet? If that is a big deal we can just an addition methods like `PolygonWithError`. But that's not great.

**Comment by thisisaaronland** [comment]
I think the consensus is that pre 1.0 things are considered to be a "moving target" and there is an expectation that changes may still ripple down to other people's code. That's been my approach but I didn't want to assume it was yours :-)

**Comment by paulmach** [comment]
I merged https://github.com/paulmach/orb/pull/87 to change the signature to return an error. This is the only change in v0.7.0 so if there are issues I can pull that release. I don't expect there to be issues.

**Comment by thisisaaronland** [comment]
Thanks!
