### ISSUE TITLE
WKB Encode/Decode

### ISSUE THREAD

**Issue by gmonk** [paulmach/orb#91]
Is it possible to encode/decode between wkb and geojson similar to https://rodic.fr/wp-content/uploads/2015/11/geom_converter.html

**Which takes** 
010500000001000000010200000004000000554d95b3c8d45bc0cf4ef2e5522241403448c153c8d45bc023a12de752224140c39acaa2b0d45bc0e2b19fc5522241402b31a62dadd45bc090ffffcc52224140

**And decodes it to the following**

{"type":"MultiLineString","coordinates":[[[-111.32474984722406,34.26815485316694],[-111.324727,34.268155],[-111.323281,34.268151],[-111.32306996564573,34.26815187930981]]]}

I am trying to take a geojson feature collection and encode that into WKB to be inserted into postgis  but documentation   seems very sparse on both topics

**Comment by paulmach** [comment]
That is hex encoded wkb. You first need to decode it into byte data with [encoding.hex.DecodeString](https://pkg.go.dev/encoding/hex#DecodeString). Then you can use this package to to decode the geometry using [wkb.Unmarshal](https://pkg.go.dev/github.com/paulmach/orb/encoding/wkb#Unmarshal).

To insert you can encode it as wkb, and insert that.

**Comment by gmonk** [comment]
Perfect ... Thank you
