### ISSUE TITLE
Check function spelling (Haversine)

### ISSUE THREAD

**Issue by pelter** [paulmach/orb#96]
Within orb/geo/length.go, there is a function named LengthHaversign; presumably this should be LengthHaversine?

[](https://github.com/paulmach/orb/blob/dcade4901baea0727377ccf7c4aab2addd92d152/geo/length.go#L16)
[](https://github.com/paulmach/orb/blob/dcade4901baea0727377ccf7c4aab2addd92d152/geo/length.go#L14)
[](https://github.com/paulmach/orb/blob/dcade4901baea0727377ccf7c4aab2addd92d152/geo/length_test.go#L16)

**Comment by paulmach** [comment]
Thank you https://github.com/paulmach/orb/pull/97
