### ISSUE TITLE
I got some error when i zoom the LineString map to high level on mapbox-gl.js

### ISSUE THREAD

**Issue by liujiusheng** [paulmach/orb#99]
![image](https://user-images.githubusercontent.com/9045263/163908637-e1ec7cda-3c5a-4848-b141-434f732c5a54.png)

![image](https://user-images.githubusercontent.com/9045263/163908683-afec29eb-1ef5-426e-b0a8-2b1026b3337b.png)

**Comment by paulmach** [comment]
Can you be more clear about how your error relates to this library.

**Comment by liujiusheng** [comment]
> Can you be more clear about how your error relates to this library.

Thanks.I have found the problem, I forgot to Clip the tiles.
